/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Mobile mobile = new Mobile();
        Andriod andriod = new Andriod();
        IPhone iPhone = new IPhone();

        mobile.call("aaa");
        andriod.call("aaa");
        iPhone.call("aaa");
        mobile.getInfo();
//        System.out.println(new App().getGreeting());
    }
}
