/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Mobile mobile = new Mobile("boom", "black", "sumsang");
        Andriod andriod = new Andriod("guochanshouji", "black", "huawei");
        IPhone iPhone = new IPhone("gaodashang", "white", "apple");

        mobile.call("aaa");
        andriod.call("aaaaaaaaaaaaafddsfsdfdsfaaaa");
        iPhone.call("aaa");
        mobile.getInfo();
        Person li = new Person("li");
        li.setMobile(andriod);
        li.useMobile("waht ?");


    }
}
